// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_games_played = "CgkIz7Kul8IFEAIQAw"; // <GPGSID>
        public const string achievement_collect_1500_stars = "CgkIz7Kul8IFEAIQDA"; // <GPGSID>
        public const string achievement_collect_all_customizables = "CgkIz7Kul8IFEAIQDg"; // <GPGSID>
        public const string event_times_crashed = "CgkIz7Kul8IFEAIQAg"; // <GPGSID>
        public const string achievement_crash_1000_times = "CgkIz7Kul8IFEAIQCg"; // <GPGSID>
        public const string achievement_crash_10_times = "CgkIz7Kul8IFEAIQCA"; // <GPGSID>
        public const string achievement_play_1000_games = "CgkIz7Kul8IFEAIQBg"; // <GPGSID>
        public const string achievement_play_100_games = "CgkIz7Kul8IFEAIQBw"; // <GPGSID>
        public const string achievement_play_250_games = "CgkIz7Kul8IFEAIQBQ"; // <GPGSID>
        public const string leaderboard_times_crashed = "CgkIz7Kul8IFEAIQEA"; // <GPGSID>
        public const string achievement_play_50_games = "CgkIz7Kul8IFEAIQBA"; // <GPGSID>
        public const string leaderboard_times_played = "CgkIz7Kul8IFEAIQDw"; // <GPGSID>
        public const string achievement_crash_100_times = "CgkIz7Kul8IFEAIQCQ"; // <GPGSID>
        public const string event_collected_stars = "CgkIz7Kul8IFEAIQAQ"; // <GPGSID>
        public const string achievement_collect_150_stars = "CgkIz7Kul8IFEAIQCw"; // <GPGSID>
        public const string achievement_collect_3000_stars = "CgkIz7Kul8IFEAIQDQ"; // <GPGSID>

}

